server:
  port: ${SERVER_PORT}

spring:

  application:
    name: ejka

  servlet:
    multipart:
      max-file-size: ${SERVLET_MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${SERVLET_MULTIPART_MAX_REQUEST_SIZE}

  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
    driver-class-name: ${POSTGRES_DB_DRIVER}

  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  rabbitmq:
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}

rabbitmq:
  exchange: image.exchange
  queues:
    image-processing:
      name: ${RABBIT_QUEUE_REQUESTS:q.image.processing.requests}
      routing-key: image.request.rk
    image-responses:
      name: ${RABBIT_QUEUE_RESULTS:q.image.processing.responses}
      routing-key: image.response.rk

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

minio:
  enpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  buckets:
    products: ${MINIO_PRODUCTS_BUCKET_NAME}