server:
  port: ${SERVER_PORT}

spring:

  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
    driver-class-name: ${POSTGRES_DB_DRIVER}

  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}