spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/ejka
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6380

jwt:
  secret: 5d0168f7645e14762f22c78398529a3a762c468b0beb412eff4d8f46b122b802
  access:
    expiration: 604800000
  refresh:
    expiration: 604800000